### ISSUE TITLE
Problems previewing nested block grids in v13

### ISSUE THREAD

**Issue by richarth** [rickbutterfield/Our.Umbraco.BlockPreview#47] opened 2024-02-29 16:43 UTC
Hi,

Firstly, thanks for the excellent package. It's been a massive help.

We have a site which has some block grids nested in a block grid.  We're using this package to give editors a friendlier editing experience in the back office whereby they can see what they are changing.  When running the site on Umbraco 12 both the front end and back office are rendering fine.

After upgrading the site to v13 the front end is rendering fine, but nothing is rendering in the back office.  Having dug into it a little I found that the models being passed into the component views were null.

As the front end is rendering fine I suspect that it's a problem with this package, but I may be wrong on that.  I'm not sure if they maybe changed the grid data format in v13.

I also tried running the test sites associated with the package.  Again the v12 site was working fine, but when previewing the homepage of the v13 site all of the RTE blocks are displaying [Object object] rather than the RTE contents.

I've attached a minimal site that demos the issue.  If you run the site and visit the homepage you'll see the quick links being output.  If you however try and edit the homepage in the backoffice you'll see there is a blank space where the quick links should be output.  I've reused the login details from the packages test sites for my test site.

[block-preview-test.zip](https://github.com/rickbutterfield/Umbraco.Community.BlockPreview/files/14450971/block-preview-test.zip)

I'd be grateful if you could have a look into this please.

Thanks

Richard

**Comment by rickbutterfield** [comment] 2024-03-14 12:53
Hey @richarth! Firstly, thank you for the comprehensive information and the test site, this has been super helpful in tracking down the bug!

This will be fixed in v1.8.1, releasing later today or early tomorrow.

**Comment by rickbutterfield** [comment] 2024-03-14 13:31
@richarth v1.8.1 is released now! I've just tried it against your demo site, and it is now working as intended by simply updating to the latest version.

**Closed as completed by rickbutterfield** 2024-03-14 13:31 UTC

**Comment by richarth** [comment] 2024-03-14 16:08
Thanks for fixing @rickbutterfield. Glad the information helped.

I'll give my site a try over the next few days.

Thanks again for the great package.

**Comment by richarth** [comment] 2024-03-18 13:52
Hi,

I've tested my site and can confirm that the update fixed the issue.

Thanks again.

Richard
